### ISSUE TITLE
Invalid baseIRI when querying a local JSON-LD file

### ISSUE THREAD

**Issue by pheyvaer** [comunica/comunica#1044]
#### Issue type:

- :bug: Bug 

____
#### Description:

When I query a local JSON-LD file with this command

```shell
comunica-sparql-file "/Users/pheyvaer/Development/test.jsonld" -q "SELECT * WHERE {?s ?p ?o}"
````

 I get the following error 

```
Found invalid baseIRI '/Users/pheyvaer/Development/test.jsonld' for value '/Users/pheyvaer/Development/test.jsonld'
```
The error doesn't occur when adding `file://` to the path:

```shell
comunica-sparql-file "file:///Users/pheyvaer/Development/test.jsonld" -q "SELECT * WHERE {?s ?p ?o}"
````
____
#### Environment:
```shell
$ comunica-sparql-file -v
```
| software         | version
| ---------------- | -------
| Comunica Engine  | 2.3.0 
| node             | v14.19.2
| npm              | 8.10.0
| yarn             | 1.22.5
| Operating System | darwin (Darwin 21.5.0)

#### Crash log:

-----

## Bounty

A [bounty](https://comunica.dev/association/bounties/) has been placed on this issue by:

| |
|-|
| [<img alt="Comunica Association" src="https://comunica.dev/img/comunica_red.svg" height="50">](https://comunica.dev/association/) |
| €136 |

[Click here to learn more](https://comunica.dev/association/bounty_process/) if you're interested in claiming this bounty by resolving this issue.

**Comment by rubensworks** [comment]
The fix for this should be easy: at the location where the baseIRI is set (I think actor-init-query), we should ensure that `file://` is prepended if we detect that we're working with a file path.

**Comment by andrewzhurov** [comment]
As discussed with @rubensworks, I will work on this issue via the Comunica Association.

**Comment by andrewzhurov** [comment]
Would we like to have support for relative paths as well?

**Comment by rubensworks** [comment]
@andrewzhurov Yes, those cases can occur as well!

**Comment by rubensworks** [comment]
Hi @andrewzhurov, just checking in to see how you are progressing with this bounty?

**Comment by andrewzhurov** [comment]
Hi @rubensworks, I had a shift in priorities and work got on pause, sadly.
I've uploaded WIP so far and created a draft PR.
Logic is written and manually tested on Linux to work. That bit was pretty easy.
It seems it should work on MacOS and Windows as well, since it [relies on `path.resolve`](https://github.com/comunica/comunica/blob/ef2a2955f0ac7e6c1f8e55e85e60489f5b5445fd/packages/actor-init-query/lib/cli/CliArgsHandlerBase.ts) to handle URIfication. But I have no way to test that.
I paused when been writing tests, so they are WIP.
Testing is a bit more trickier, because behaviour (URIs) are platform-dependent.
I've been trying to find a way to write platform dependent tests but had little luck with it.
Taken an alternative route of testing platform-independent bits and relying that platform-dependent bits are performing as expected. That is a pretty safe assumption, given that relative path -> IRI is being handled by `path.resolve`.

I plan to get back on it next month, but let me know if we'd need it more promptly.
Thanks for checking in.

**Comment by rubensworks** [comment]
Thanks for the update @andrewzhurov!

**Comment by andrewzhurov** [comment]
Looks like it's been resolved in version 2.3.1-alpha.26.0

From version 2.3.1-alpha.26.0 onwards (presumably all versions, although tested only some) `comunica-sparql-file` works with local fs paths on my end (Linux), and I'd expect it to work on other OSes the same

A bit of technical details
Version 2.5.0 uses [ActorDereferenceFile](https://github.com/comunica/comunica/blob/c585090b3c1bb84ae08628a573a788ed3f87ce85/packages/actor-dereference-file/lib/ActorDereferenceFile.ts) to handle dereference of local files, and it supports files as URIs (file://...) and local fs paths

@pheyvaer could you let me know whether this issue still happens on 2.5.0?

**Comment by rubensworks** [comment]
Still doesn't work for me @andrewzhurov.
Are you sure you're testing with a JSON-LD file?

As a reminder, the problem is that [the `baseIRI` is not correctly set](https://github.com/comunica/comunica/issues/1044#issuecomment-1212894460)

**Comment by andrewzhurov** [comment]
Ah, thanks for the catch, @rubensworks! Something got crossed in my head..
Perhaps due to shallow familiarity with the project, on the plus side it's been a good opportunity to give it a deeper dive.=)

`baseIRI` seems to originate from [ActorDereferenceRDFParse, here](https://github.com/comunica/comunica/blob/e4b91d5a254e0ead57e5ce26d8572e95a5e5c478/packages/actor-dereference-rdf-parse/lib/ActorDereferenceRdfParse.ts#L39).
Prepending it with `file://` by default would seem to solve the issue.

Alternatively, we could prepend sources as soon as possible, so the rest of the engine is guaranteed to work with URIs, perhaps that would be a more robust approach, although I lack domain knowledge to speculate.:)
If that would be so indeed, then it seems the earliest we can do, so it affects both command line engine _and JS API engines_, is to patch sources [in QueryEngineBase, here](https://github.com/comunica/comunica/blob/e4b91d5a254e0ead57e5ce26d8572e95a5e5c478/packages/actor-init-query/lib/QueryEngineBase.ts#L116) (they are in `context`)

Which option do you think would be the best, @rubensworks?

**Comment by rubensworks** [comment]
On second thought, I think actor-init-query won't be the right place to set the baseIRI, since this IRI is possible only determined later (e.g. if the file exists behind some redirects).

> baseIRI seems to originate from [ActorDereferenceRDFParse, here](https://github.com/comunica/comunica/blob/e4b91d5a254e0ead57e5ce26d8572e95a5e5c478/packages/actor-dereference-rdf-parse/lib/ActorDereferenceRdfParse.ts#L39).
Prepending it with file:// by default would seem to solve the issue.

So yes, somewhere there would make sense.
However, we should only add the scheme if no scheme is present yet, and if we're dereferencing files. So there might be a way to do this via `ActorDereferenceFile`.

**Comment by andrewzhurov** [comment]
Aha, that's a good idea!
One way to do so would be to accrete `DereferenceOutput` with `baseIRI`, in [`ActorDereferenceFile`, here](https://github.com/comunica/comunica/blob/e4b91d5a254e0ead57e5ce26d8572e95a5e5c478/packages/actor-dereference-file/lib/ActorDereferenceFile.ts#L31), and return it as metadata to those who's interested in it downstream, in [`ActorDereferenceRDFParse`, here](https://github.com/comunica/comunica/blob/e4b91d5a254e0ead57e5ce26d8572e95a5e5c478/packages/actor-dereference-rdf-parse/lib/ActorDereferenceRdfParse.ts#L39).

Alternatively we could modify `url` itself in `ActorDereferenceFile`, although I fear that may be invasive..

**Comment by rubensworks** [comment]
> One way to do so would be to accrete DereferenceOutput with baseIRI, in [ActorDereferenceFile, here](https://github.com/comunica/comunica/blob/e4b91d5a254e0ead57e5ce26d8572e95a5e5c478/packages/actor-dereference-file/lib/ActorDereferenceFile.ts#L31), and return it as metadata to those who's interested in it downstream, in [ActorDereferenceRDFParse, here](https://github.com/comunica/comunica/blob/e4b91d5a254e0ead57e5ce26d8572e95a5e5c478/packages/actor-dereference-rdf-parse/lib/ActorDereferenceRdfParse.ts#L39).

Something like that might work indeed.

**Comment by andrewzhurov** [comment]
As I'm giving it another thought, it seems to me that the second option is what we'd like to have.
At the point where we successfuly dereferenced a file we are safe to convert that ambiguous string that user supplied (that turned out to be a file system path) to a file URL, passing it further on, so the downstream does not need to guess what that string is.
That can be done in the same [ActorDereferenceFile, here](https://github.com/comunica/comunica/blob/e4b91d5a254e0ead57e5ce26d8572e95a5e5c478/packages/actor-dereference-file/lib/ActorDereferenceFile.ts#L31)
I'll carry on with that solution, as it seems most sensible to me atm, I'll be glad to learn that I'm mistaken somewhere and there is a better approach

**Comment by rubensworks** [comment]
@pheyvaer I just released Comunica `2.5.3-alpha.36.0`. Could you have a look to see if the original issue is also solved on your end?
If so, we can finalize the bounty for @andrewzhurov.

**Comment by pheyvaer** [comment]
It works with `2.5.3-alpha.37.0`. 🎉

**Comment by rubensworks** [comment]
Super, thanks for checking @pheyvaer!

@andrewzhurov Feel free to post an invoice on [Open Collective](https://opencollective.com/comunica-association) to finalize the bounty (feel free to mail me if there are any issues/questions). Thanks again for the great work!

**Comment by andrewzhurov** [comment]
Great to see it shipped in, I hope this fix makes our lives a bit more joyful here and there.:)
It's been a good opportunity to get to know the project closer
Thanks for reporting it, @pheyvaer
Thanks for having a bounty placed on it, @rubensworks, helps to commit to it
