### ISSUE TITLE
crash in ActorRdfJoinMultiBind

### ISSUE THREAD

**Issue by balhoff** [comunica/comunica#1404]
#### Issue type:

- :bug: Bug 

____
#### Description:

Running a particular query which uses `FILTER NOT EXISTS` results in `TypeError: Cannot read properties of undefined (reading 'merge')`. Unfortunately I haven't narrowed down this to a very specific problem, but I can provide the data and query here (attached). I'm running `comunica-sparql-file`:

```
node bin/query.js data.ttl --file query.rq
```
____
#### Environment:

```
| software         | version
| ---------------- | -------
| Comunica Engine  | 3.2.0 (dev)
| node             | v22.4.1
| npm              | 10.8.1
| yarn             | 1.22.22
| Operating System | darwin (Darwin 23.5.0)
```

#### Crash log:

```
/Users/jim/Documents/Source/comunica-source-annotate/packages/actor-rdf-join-inner-multi-bind/lib/ActorRdfJoinMultiBind.js:46
            const bindingsMerger = (subBindings) => subBindings.merge(bindings);
                                                                ^

TypeError: Cannot read properties of undefined (reading 'merge')
    at SimpleTransformIterator.bindingsMerger [as _map] (/Users/jim/Documents/Source/comunica-source-annotate/packages/actor-rdf-join-inner-multi-bind/lib/ActorRdfJoinMultiBind.js:46:65)
    at SimpleTransformIterator._readAndTransformSimple (/Users/jim/Documents/Source/comunica-source-annotate/node_modules/asynciterator/dist/asynciterator.js:1362:79)
    at SimpleTransformIterator._read (/Users/jim/Documents/Source/comunica-source-annotate/node_modules/asynciterator/dist/asynciterator.js:1339:14)
    at SimpleTransformIterator._fillBuffer (/Users/jim/Documents/Source/comunica-source-annotate/node_modules/asynciterator/dist/asynciterator.js:1001:18)
    at MultiTransformIterator.destinationFillBuffer (/Users/jim/Documents/Source/comunica-source-annotate/node_modules/asynciterator/dist/asynciterator.js:1281:35)
    at MultiTransformIterator.emit (node:events:520:28)
    at /Users/jim/Documents/Source/comunica-source-annotate/node_modules/asynciterator/dist/asynciterator.js:234:42
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)

Node.js v22.4.1
```

[error.tgz](https://github.com/user-attachments/files/16396463/error.tgz)

**Comment by rubensworks** [comment]
I suspect this is caused by the same problem as in #1403.
After I released 3.2.1, could you try it again to see if the problem goes away?

**Comment by balhoff** [comment]
The error still occurs in `v3.2.1`, but it goes away with the latest on `master` at 520f39691ea13b354b4d0779f7b02b20f1fcd506.

**Comment by balhoff** [comment]
I did a git bisect and it seems like this commit may have fixed it: 328d3f6fe3e17033389f1b716d2c98352d5f1b28.

**Comment by rubensworks** [comment]
Aha, that would explain it indeed. Thanks for checking!
Will already close this one then.
